### ISSUE TITLE
[Handbook] Define style of the notes/callouts in content pages

### ISSUE THREAD

**Issue by andradaradu** [greenpeace/planet4#162]
### Brief summary of task:

Revisit the style of the notes/callouts in content pages (see yellow notes here for example https://planet4.greenpeace.org/content/blocks/) to see if these can be less intense.

### Resources:

[P4 Design System](https://p4-designsystem.greenpeace.org/05f6e9516/p/60f977-colours/b/308811)

**Comment by unnati2201** [comment]
Hello,
Here less intense mean we need to reduce the color intensity of Yellow, right?

**Comment by GP-Dan-Tovbein** [comment]
Yes. You can check it out this url https://p4-designsystem.greenpeace.org/05f6e9516/p/60f977-colours/b/308811 and find a new yellow color that accurate with rest of the pallete

**Comment by gerardsegarra** [comment]
@unnati2201 are you working on this? If not I can do it :)

**Comment by comzeradd** [comment]
Since it's inactive for some time now, I'm re-assigning. There are plenty of tickets to pick up something new :)

**Comment by gerardsegarra** [comment]
I'm sorry too, something just came up and I'm not sure I'll be able to dedicate time to this :(

**Comment by wesleymiles** [comment]
Hi, i can take this one.

**Comment by suzi-greenpeace** [comment]
thanks Wes! let us know if you have any questions about our design system.


– – – – – – – – – – – – – – – – – – – – – –
*Suzi Grishpul* (they/them/theirs <https://www.mypronouns.org/they-them>)

Interim Head of Engagement Systems
&  Planet 4 Product Manager
Greenpeace International <https://www.greenpeace.org/international>

Based in: Denver, US (UTC-6)
Schedule a meeting with me <https://calendly.com/suzi-grishpul/meet>

**Comment by wesleymiles** [comment]
Thanks, Suzi! 

Here's what i've done so far:
- cloned the `planet4-docker-compose` repo locally
- installed the child theme `planet4-child-theme-handbook`
- created a test page with the notes/callouts
- tested out a replacement light green pulled from the design system colors = #EAFEE7.

What I'm not sure on is the next steps. Is this ask also to figure out how to make the change via css? If so, i got stuck on how to do that because i'm not quite sure how the palette.scss is applying colors, and probably could use a walk-through. This is my first github issue so go easy on me :) 

Thanks!

**Comment by suzi-greenpeace** [comment]
Hey @wesleymiles , sorry for the delay, we're a bit short-staffed at the moment. I'll see if we can get a dev to help you out with this in the next few weeks. Thanks for taking this on!

**Comment by comzeradd** [comment]
Closing this as we implemented the new visual identity and colors have completely changed in the meantime
